package thrift;/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class NeedAndReal implements org.apache.thrift.TBase<NeedAndReal, NeedAndReal._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NeedAndReal");

  private static final org.apache.thrift.protocol.TField DEPARTMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("department", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NEED_FIELD_DESC = new org.apache.thrift.protocol.TField("need", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField REAL_FIELD_DESC = new org.apache.thrift.protocol.TField("real", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new NeedAndRealStandardSchemeFactory());
    schemes.put(TupleScheme.class, new NeedAndRealTupleSchemeFactory());
  }

  public String department; // required
  public int need; // required
  public int real; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DEPARTMENT((short)1, "department"),
    NEED((short)2, "need"),
    REAL((short)3, "real");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DEPARTMENT
          return DEPARTMENT;
        case 2: // NEED
          return NEED;
        case 3: // REAL
          return REAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NEED_ISSET_ID = 0;
  private static final int __REAL_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DEPARTMENT, new org.apache.thrift.meta_data.FieldMetaData("department", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NEED, new org.apache.thrift.meta_data.FieldMetaData("need", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.REAL, new org.apache.thrift.meta_data.FieldMetaData("real", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NeedAndReal.class, metaDataMap);
  }

  public NeedAndReal() {
  }

  public NeedAndReal(
    String department,
    int need,
    int real)
  {
    this();
    this.department = department;
    this.need = need;
    setNeedIsSet(true);
    this.real = real;
    setRealIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NeedAndReal(NeedAndReal other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDepartment()) {
      this.department = other.department;
    }
    this.need = other.need;
    this.real = other.real;
  }

  public NeedAndReal deepCopy() {
    return new NeedAndReal(this);
  }

  @Override
  public void clear() {
    this.department = null;
    setNeedIsSet(false);
    this.need = 0;
    setRealIsSet(false);
    this.real = 0;
  }

  public String getDepartment() {
    return this.department;
  }

  public NeedAndReal setDepartment(String department) {
    this.department = department;
    return this;
  }

  public void unsetDepartment() {
    this.department = null;
  }

  /** Returns true if field department is set (has been assigned a value) and false otherwise */
  public boolean isSetDepartment() {
    return this.department != null;
  }

  public void setDepartmentIsSet(boolean value) {
    if (!value) {
      this.department = null;
    }
  }

  public int getNeed() {
    return this.need;
  }

  public NeedAndReal setNeed(int need) {
    this.need = need;
    setNeedIsSet(true);
    return this;
  }

  public void unsetNeed() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NEED_ISSET_ID);
  }

  /** Returns true if field need is set (has been assigned a value) and false otherwise */
  public boolean isSetNeed() {
    return EncodingUtils.testBit(__isset_bitfield, __NEED_ISSET_ID);
  }

  public void setNeedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NEED_ISSET_ID, value);
  }

  public int getReal() {
    return this.real;
  }

  public NeedAndReal setReal(int real) {
    this.real = real;
    setRealIsSet(true);
    return this;
  }

  public void unsetReal() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REAL_ISSET_ID);
  }

  /** Returns true if field real is set (has been assigned a value) and false otherwise */
  public boolean isSetReal() {
    return EncodingUtils.testBit(__isset_bitfield, __REAL_ISSET_ID);
  }

  public void setRealIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REAL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DEPARTMENT:
      if (value == null) {
        unsetDepartment();
      } else {
        setDepartment((String)value);
      }
      break;

    case NEED:
      if (value == null) {
        unsetNeed();
      } else {
        setNeed((Integer)value);
      }
      break;

    case REAL:
      if (value == null) {
        unsetReal();
      } else {
        setReal((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DEPARTMENT:
      return getDepartment();

    case NEED:
      return Integer.valueOf(getNeed());

    case REAL:
      return Integer.valueOf(getReal());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DEPARTMENT:
      return isSetDepartment();
    case NEED:
      return isSetNeed();
    case REAL:
      return isSetReal();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NeedAndReal)
      return this.equals((NeedAndReal)that);
    return false;
  }

  public boolean equals(NeedAndReal that) {
    if (that == null)
      return false;

    boolean this_present_department = true && this.isSetDepartment();
    boolean that_present_department = true && that.isSetDepartment();
    if (this_present_department || that_present_department) {
      if (!(this_present_department && that_present_department))
        return false;
      if (!this.department.equals(that.department))
        return false;
    }

    boolean this_present_need = true;
    boolean that_present_need = true;
    if (this_present_need || that_present_need) {
      if (!(this_present_need && that_present_need))
        return false;
      if (this.need != that.need)
        return false;
    }

    boolean this_present_real = true;
    boolean that_present_real = true;
    if (this_present_real || that_present_real) {
      if (!(this_present_real && that_present_real))
        return false;
      if (this.real != that.real)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(NeedAndReal other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    NeedAndReal typedOther = (NeedAndReal)other;

    lastComparison = Boolean.valueOf(isSetDepartment()).compareTo(typedOther.isSetDepartment());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDepartment()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.department, typedOther.department);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNeed()).compareTo(typedOther.isSetNeed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNeed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.need, typedOther.need);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReal()).compareTo(typedOther.isSetReal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.real, typedOther.real);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NeedAndReal(");
    boolean first = true;

    sb.append("department:");
    if (this.department == null) {
      sb.append("null");
    } else {
      sb.append(this.department);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("need:");
    sb.append(this.need);
    first = false;
    if (!first) sb.append(", ");
    sb.append("real:");
    sb.append(this.real);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NeedAndRealStandardSchemeFactory implements SchemeFactory {
    public NeedAndRealStandardScheme getScheme() {
      return new NeedAndRealStandardScheme();
    }
  }

  private static class NeedAndRealStandardScheme extends StandardScheme<NeedAndReal> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NeedAndReal struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DEPARTMENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.department = iprot.readString();
              struct.setDepartmentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NEED
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.need = iprot.readI32();
              struct.setNeedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REAL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.real = iprot.readI32();
              struct.setRealIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NeedAndReal struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.department != null) {
        oprot.writeFieldBegin(DEPARTMENT_FIELD_DESC);
        oprot.writeString(struct.department);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NEED_FIELD_DESC);
      oprot.writeI32(struct.need);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(REAL_FIELD_DESC);
      oprot.writeI32(struct.real);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NeedAndRealTupleSchemeFactory implements SchemeFactory {
    public NeedAndRealTupleScheme getScheme() {
      return new NeedAndRealTupleScheme();
    }
  }

  private static class NeedAndRealTupleScheme extends TupleScheme<NeedAndReal> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NeedAndReal struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDepartment()) {
        optionals.set(0);
      }
      if (struct.isSetNeed()) {
        optionals.set(1);
      }
      if (struct.isSetReal()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetDepartment()) {
        oprot.writeString(struct.department);
      }
      if (struct.isSetNeed()) {
        oprot.writeI32(struct.need);
      }
      if (struct.isSetReal()) {
        oprot.writeI32(struct.real);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NeedAndReal struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.department = iprot.readString();
        struct.setDepartmentIsSet(true);
      }
      if (incoming.get(1)) {
        struct.need = iprot.readI32();
        struct.setNeedIsSet(true);
      }
      if (incoming.get(2)) {
        struct.real = iprot.readI32();
        struct.setRealIsSet(true);
      }
    }
  }

}

